config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'topics#index'
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy

  validates_presence_of :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  
  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    @notification = @comment.notifications.build(user_id: @topic.user_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.js { render :index }
        unless @comment.topic.user_id == current_user.id
          Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'comment_created', {
           message: 'あなたの作成したブログにコメントが付きました'
         })
       end
       Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
        })
      else
        format.html { redirect_to topic_path(@topic), notice: 'コメントを入力してください。' }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_path(@topic), notice: 'コメントを更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to topic_path(@topic), notice: "コメントを削除しました！" }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @comment = Comment.find(params[:id])
      @topic = @comment.topic
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <%= f.error_messages! %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit 'コメントする', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg fa-white",title: "編集" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-times fa-lg fa-white",title: "削除", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
  <h1>コメントの編集</h1>
  <%= form_for([@topic,@comment], remote: true) do |f| %>
    <%= f.error_messages! %>
    <%= f.hidden_field :topic_id %>
    <div class="field">
      <%= f.label :コメント %><br>
      <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
    </div>
    <div class="actions">
      <%= f.submit '変更する', class: 'btn btn-default btn-block' %>
      <br>
      <%= link_to '戻る', topic_path(@topic), class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')