config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'topics#index'
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @topics = Topic.all.order("id DESC")
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: '投稿しました' }
        NoticeMailer.sendmail_topic(@topic).deliver
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: '投稿を更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: '投稿を削除しました' }
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :game_title, :content)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <%= f.error_messages! %>

  <div class="field">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title, class: 'form-control', autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :ゲームタイトル %><br>
    <%= f.text_field :game_title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.text_area :content, class: 'form-control', placeholder: '今なにしてる？' %>
  </div>
  <div class="actions">
    <%= f.submit "投稿する", class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
  <h1>編集画面</h1>

  <%= render 'form' %>

  <%= link_to '詳細', @topic, class: 'btn btn-default' %>
  <%= link_to '戻る', topics_path, class: 'btn btn-default' %>
</div>

app/views/topics/index.html.erb
<div class="topic-wrapper col-md-4 col-md-offset-4 col-sm-10">
  <div class="new-topic-box">
    <%= link_to '新しく投稿する', new_topic_path %>
  </div>
  <% @topics.each do |topic| %>
    <div class="topic-box">
      <div class="user-box">
        <%= profile_img(topic.user) if profile_img(topic.user) %>
        <%= topic.user.name %>
        <span class="pull-right"><%= topic.created_at.strftime("%y/%m/%d %p %l:%M") %></span>
      </div>
      <div class="title-box">
        <span class="title-tag"><%= topic.title %></span>
        <span class="game-title-tag"><%= topic.game_title %></span>
      </div>
      <div class="content-box">
        <%= topic.content %>
      </div>
      <div class="btn-box">
        <%= link_to 'トピックを見る', topic, class: 'btn btn-default' %>
        <% if topic.user_id == current_user.id %>
          <%= link_to '編集', edit_topic_path(topic), class: 'btn btn-default' %>
          <%= link_to '削除', topic, class: 'btn btn-danger pull-right', method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
  <h1>新規投稿</h1>

  <%= render 'form' %>

  <%= link_to '戻る', topics_path, class: 'btn btn-default' %>
</div>

app/views/topics/show.html.erb
<div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
  <div class="show-topic-box">
    <div class="user-box">
      <%= profile_img(@topic.user) if profile_img(@topic.user) %>
      <%= @topic.user.name %>
      <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
    </div>
    <div class="title-box">
      <span class="title-tag"><%= @topic.title %></span>
      <span class="game-title-tag"><%= @topic.game_title %></span>
    </div>
    <div class="content-box">
      <%= @topic.content %>
    </div>
    <div class="btn-box">
      <% if @topic.user_id == current_user.id %>
        <%= link_to '編集', edit_topic_path(@topic), class: 'btn btn-default' %>
      <% end %>
      <%= link_to '戻る', topics_path, class: 'btn btn-default' %>
    </div>
    <hr>
    <p>コメント一覧</p>
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
  </div>
</div>