config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'topics#index'
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  mount_uploader :avatar, AvatarUploader

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>", class="pull-right">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "フォロー解除", class: "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="user-wrapper col-md-4 col-md-offset-4 col-sm-10">
  <h2>ユーザー一覧</h2>
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
      <div class="user-box follow-user-box">
        <%= profile_img(user) %>
        <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-default pull-right' %>
        <%= link_to 'ユーザー詳細', user_path(user), class: 'btn btn-default pull-right' %>
        <ul>
          <li><%= user.name %></li>
          <li><%= user.email %></li>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>ユーザーデータ</h2>
<div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
  <div class="user-detail-name-box">
    <%= profile_img(@user) %>
    <%= @user.name %>
  </div>
  <div class="user-detail-btn-box">
    <%= link_to '戻る', users_path, class: 'btn btn-default pull-left' %>
    <% if @user.id != current_user.id %>
      <%= render partial: 'follow_form', locals: { user: @user } if signed_in?   %>
      <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class: 'btn btn-default pull-right' %>
    <% end %>
  </div>
  <div class="user-detail-follow-box">
    <h4>フォローユーザー</h4>
    <% @user.followed_users.each do |follow| %>
    <ul>
      <li><%= follow.name %></li>
    </ul>
    <% end %>
  </div>
  <div class="user-detail-follow-box">
    <h4>フォロワーユーザー</h4>
    <% @user.followers.each do |follower| %>
      <ul>
        <li><%= follower.name %></li>
      </ul>
    <% end %>
  </div>
  <h2>トピック一覧</h2>
  <% @user.topics.each do |topic| %>
    <div class="topic-box">
      <div class="user-box">
        <%= profile_img(topic.user) if profile_img(topic.user) %>
        <%= topic.user.name %>
        <span class="pull-right"><%= topic.created_at.strftime("%y/%m/%d %p %l:%M") %></span>
      </div>
      <div class="title-box">
        <span class="title-tag"><%= topic.title %></span>
        <span class="game-title-tag"><%= topic.game_title %></span>
      </div>
      <div class="content-box">
        <%= topic.content %>
      </div>
      <div class="btn-box">
        <%= link_to 'トピックを見る', topic, class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>