config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'topics#index'
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameFlat</title>
  <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if user_signed_in? %>
    <script>
      var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
        encrypted: true
      });

      var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
      channel.bind('comment_created', function(data) {
        alert(data.message);
      });
      channel.bind('notification_created', function(data) {
        $('#unread_count').html(data.unread_counts);
      });
    </script>
  <% end %>
</head>
<body>
  <header>
    <%= link_to "Game Flat", topics_path, class: 'logo' %>
    <div class="pull-right">
      <% if user_signed_in? %>
        <%= link_to  notifications_index_path, title: "通知" do %>
          <i class="fa fa-bell fa-1x fa-btn"><span id="unread_count"><%= @notifications_count %></span></i>
        <% end %>
        <%= link_to users_path, title: "ユーザー検索" do %>
          <i class="fa fa-search fa-1x fa-btn"></i>
        <% end %>
        <%= link_to conversations_path, title: "メッセージ" do %>
          <i class="fa fa-commenting fa-1x fa-btn"></i>
        <% end %>
        <%= link_to edit_user_registration_path, title: "マイページ" do %>
          <i class="fa fa-user fa-1x fa-btn"></i>
        <% end %>
        <%= link_to destroy_user_session_path, title: "ログアウト", method: :delete do %>
          <i class="fa fa-sign-out fa-1x fa-btn"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, title: "ログイン" do %>
          <i class="fa fa-sign-in fa-1x fa-btn"></i>
        <% end %>
        <%= link_to new_user_registration_path, title: "サインアップ" do %>
          <i class="fa fa-user-plus fa-1x fa-btn"></i>
        <% end %>
      <% end %>
    </div>
  </header>
  <p class="flash"><%= notice %><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

  <footer>
    <p> &copy; 2016 Copyright KAZAKUMO Corp.</p>
  </footer>
</body>
</html>